### ISSUE TITLE
Can't start up docker with a fresh installation

### ISSUE THREAD

**Issue by bartrail** [jamct/node-red-pack#1]
when starting docker, the image can't boot up because `/dev/ttyACM0` cannot be found:

```
$> sudo docker-compose -f docker-compose.yml -f docker-compose.raspi.yml up -d
Starting 0af0c4885daa_noderedpack_zigbee_1
noderedpack_mqtt_1 is up-to-date
noderedpack_nodered_1 is up-to-date

ERROR: for zigbee  Cannot start service zigbee: linux runtime spec devices: error gathering device information while adding custom device "/dev/ttyACM0": no such file or directory
ERROR: Encountered errors while bringing up the project.
```

I'm trying it on a Raspberry 3B+ with Raspbian Stretch

**Comment by jamct** [comment]
I updated the setup with an additional container to support zigbee2mqtt. If you just want to start nodered, add the name of this container:
`docker-compose -f docker-compose.yml -f docker-compose.raspi.yml up -d nodered`.
I will add it to Readme.
